spring.application.name=address-consult

server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/address_consult
spring.datasource.username=address_user
spring.datasource.password=address_pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

external.cep-api.base-url=http://localhost:8081

